server:
  port: 18080
  servlet:
    context-path: /test-code
spring:
  application:
    name: test-code
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    username:
    password:
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 5
    connect-timeout: 500