server:
  port: 18082
  servlet:
    context-path: /liteFlow
liteflow:
  #规则文件路径
  rule-source: config/flow.el.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/work_flow?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    username:
    password:
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 5
    connect-timeout: 500
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  mapper-locations: classpath*:com/zukxu/demoliteflow/mapper/**/xml/*.xml